### ISSUE TITLE
"Error: Branch 'master' does not exist" even though I'm on master branch

### ISSUE THREAD

**Issue by arielelkin** [casperdcl/git-fame#12]
```
$ git fame --version
git-fame 2.5.2 (c) 2012-2018 Linus Oleander
$ git branch
  IOS-456
  IOS-123
  IOS-789
* master
$ git fame
Error: Branch 'master' does not exist.
Try --help for help.
```

**Comment by casperdcl** [comment]
That's an issue with the `ruby` version of `git-fame` (https://github.com/oleander/git-fame-rb) where you can open an issue.

If you want to use the python version, you'll have to uninstall the ruby gem git_fame, and instead `pip install git-fame` (https://github.com/casperdcl/git-fame)
