### ISSUE TITLE
Bug in the counting of lines of code

### ISSUE THREAD

**Issue by trinity357** [casperdcl/git-fame#14]
Hi,

I found a bug in the counting of lines of code. Actually, git-fame only counts one line for a block of lines owned by the same author. Here is an example :

![](https://cdn.discordapp.com/attachments/325029618560270358/516354103568367639/unknown.png)

When committing this code, as there is only one author, git-fame counts one line of code.

![](https://cdn.discordapp.com/attachments/325029618560270358/516354419693191228/unknown.png)

I propose a correction, which you can see here : https://github.com/trinity357/git-fame (The last three commits are the modifications I applied.)
After these changes, git-fame detects all the lines of code.

![](https://cdn.discordapp.com/attachments/325029618560270358/516356900871340052/unknown.png)

May I send you a pull request ?

**Comment by casperdcl** [comment]
Thanks @trinity357 - yes, do open a PR

**Comment by casperdcl** [comment]
closed by #15
