### ISSUE TITLE
automate handling of binary files

### ISSUE THREAD

**Issue by PsiPhiTheta** [casperdcl/git-fame#22]
Unsure as to why this warning comes up, but it seems like it can be safely silenced for a prettier git-fame output:

```WARNING:gitfame._gitfame:src/best_params.pickle:'utf-8' codec can't decode byte 0x80 in position 390: invalid start byte```

**Comment by casperdcl** [comment]
You should exclude binary files from analysis - for example:

```sh
git fame --excl='\.(pickle|pdf|png)$' --cost hour,month
```

**Comment by PsiPhiTheta** [comment]
In that case should these not be excluded by default by git-fame?

**Comment by casperdcl** [comment]
That would mean either

1. compiling a list of extensions that are likely to correspond to binary data (a very Windows-like non-UNIX approach), or
2. attempting automatically detect if a file is binary (might not be 100% accurate)

Raising a warning seems safest.

Happy to accept any suggestions though.
