### ISSUE TITLE
Why LOC statistic is very different compared to other tools?

### ISSUE THREAD

**Issue by bobeff** [casperdcl/git-fame#28]
I think that the tool doesn't count lines of code properly, because it shows completely different number compared to other tools like `cloc`. For example the command `git fame -t` on a repository I'm working on gives the result:
```
Total .babel: 29
Total .bash-completion: 12
Total .cfg: 8
Total .gitignore: 34
Total .json: 18
Total .markdown: 511
Total .md: 5
Total .nim: 1782
Total .nimble: 637
Total .txt: 10
Total .yml: 12
Total .zsh-completion: 51
Total commits: 842
Total ctimes: 838
Total files: 314
Total loc: 3109
```
`cloc . --vcs=git` on the same repository gives:
```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Nim                             46            869            680           4928
JSON                             2              0              0             33
YAML                             1              6              1             23
Markdown                         1              1              0              4
-------------------------------------------------------------------------------
SUM:                            50            876            681           4988
-------------------------------------------------------------------------------
```
which seems to me to be more close to the actual count for the languages which both tools detected. For bigger repositories the difference is larger. Also the Ruby version of `git fame` gives third different numbers which are even more unrealistic, but the last sentence is for their bug tracker. :) The point is that the differences which the different tools give are huge and I'm not sure on which tool to believe.

**Comment by casperdcl** [comment]
yes the python version should be more developed than the ruby one (I think, let me know if I'm missing any features).

Also the underestimated loc is a bug which will be fixed soon (#27)
