### ISSUE TITLE
recursively find repos

### ISSUE THREAD

**Issue by ddelange** [casperdcl/git-fame#29]
When running on a folder containing multiple repos (but not being a repo itself), e.g. `git-fame ~`, the app errors:
```
fatal: not a git repository (or any of the parent directories): .git
Blame: 100%|██████████| 1/1 [00:00<00:00, 183.01file/s]
error: too many arguments given outside repository
```

Since I wanted the fame for all repos on my system, I had to improvise and came up (again for `~`) with
```
git-fame --cost hour -e -M -C --sort commits `find ~ -name .git -type d -prune -exec dirname {} \; 2>/dev/null | xargs`
```

This sums over every repo in my home folder, which is what I wanted.

This however picks up trash repos that i forgot to remove from top level home or secondary repos like `~/.cache/pre-commit/XXX`, so would actually only like `git-fame ~/private_repos ~/work_repos` to exclude trash thats not in one of the provided folders.

**Comment by casperdcl** [comment]
Er so why not do that? Also you tidy that command:

```
git-fame --cost hour -eMC --sort commits \
  `find ~/private_repos ~/work_repos -type d -name .git -prune)`
```

**Comment by ddelange** [comment]
It's just a more natural CLI UX imo, esp for people unaccustomed to bash. Now I'll have to add a custom function in my bash_profile to emulate this behaviour, since I dont want to re-type this find command every time, as opposed to having it built-in and combinable with the easy to remember syntax of git-fame itself.

If you don't find it fitting to the bash philosophy 'do only one thing and do it well', maybe consider adding a recursive flag?

Either way I think this behaviour is a major use-case of this package :)

**Comment by casperdcl** [comment]
> Either way I think this behaviour is a major use-case of this package :)

For a feature release I just made 2 days ago, nice...
