### ISSUE TITLE
How to exclude multiple files & directories

### ISSUE THREAD

**Issue by kuisis** [casperdcl/git-fame#45]
Hi! Im trying to exclude multiple files or directories from output, but seems it does not work properly.
I'm not very familiar with Python or Bash, so it could be my mistake.

### Example:
First, trying to run without `--excl` flag
**Input:** `git fame -e -s`
**Output:**
```
Total commits: 80
Total ctimes: 102
Total files: 47
Total loc: 12012
```
This is ok, looks good.

Next, trying to exclude one file:
**Input:** `git fame -e -s --excl=yarn.lock`
**Output:**
```
Total commits: 80
Total ctimes: 101
Total files: 46
Total loc: 1518
```
Looks good also.

But when i try to exclude both a file AND a directory, it gives me the same result, as for without `--excl` flag
**Input:** `git fame -e -s --excl=yarn.lock,src`
**Output:**
```
Total commits: 80
Total ctimes: 102
Total files: 47
Total loc: 12012
```

When i try to add `-n` flag, it gives me the same result, as for only one `yarn.lock` file
**Input:** `git fame -e -s --excl=yarn.lock,src  -n`
**Output:**
```
Total commits: 80
Total ctimes: 101
Total files: 46
Total loc: 1518
```

**Comment by casperdcl** [comment]
when  running `git fame -h`:

> ```
> ...
> -n, --no-regex        Assume <f> are comma-separated exact matches
> ...
> ```

So since `src` is presumably a directory rather than a particular file, this won't work.

You probably need:

```
git fame -e -s --excl='yarn\.lock|^src'
```

which means `yarn.lock` and anything starting with `src`

**Comment by kuisis** [comment]
@casperdcl 
Works perfectly, thanks!
