### ISSUE TITLE
document stats

### ISSUE THREAD

**Issue by KrisThielemans** [casperdcl/git-fame#49]
I understand `loc` (lines of surviving code), `coms` (commits), but how is are `hours` etc calculated? would be nice if it would be documented what it means

**Comment by casperdcl** [comment]
`--sort=hours` or `months` must be used in conjunction with `--cost`.

- From https://github.com/casperdcl/git-fame/releases/tag/v1.8.0
  + `COCOMO|months` (person-months)
    * https://en.wikipedia.org/wiki/COCOMO
  + `commits|hours` (person-hours)
    * https://github.com/kimmobrunfeldt/git-hours/blob/8aaeee237cb9d9028e7a2592a25ad8468b1f45e4/index.js#L114-L143

**Comment by KrisThielemans** [comment]
great. On COCOMO, Wikipedia says "KLoC is the estimated number of thousands of delivered lines of code for the project,", so is this the committed lines, or surviving lines (i.e. in terms of `loc`)

**Comment by casperdcl** [comment]
I used surviving lines...
