### ISSUE TITLE
Possible documentation glitch:  "!python: event not found"

### ISSUE THREAD

**Issue by spier** [casperdcl/git-fame#55]
Hi there,

I tried out this tool today, looks nice! :)

When installing this I ran into the following issue
```
$ git config --global alias.fame "!python -m gitfame"
-bash: !python: event not found
```

My environment:
* OSX
* bash

I was able to fix it by using single quotation marks i.e.
```
$ git config --global alias.fame '!python -m gitfame'
```

Not sure if that issue is reproducible by others?
Happy to send a PR for this but I figured I first confirm this with you.

Cheers :)

**Comment by casperdcl** [comment]
ah yes, silly oversight on my part trying to support Windows. Yes, happy to accept a PR.
