### ISSUE TITLE
Add ability to exclude commits (.git-blame-ignore-revs)

### ISSUE THREAD

**Issue by shoffmeister** [casperdcl/git-fame#59]
Every once in a while, major surgery might take place on repositories, for instance to
* fix incorrectly committed line-endings
* send the complete source code through an auto-formatter (clang-format)
* ...

Any commits associated with any such activity are outliers in the contribution to the fame attribution of git repositories. It would therefore be nice if there was a feature available that allows exclusion of specific commits from fame attribution, specifically:
* the commit would be dropped from the commit count (coms)
* the commit's immediate impact of change (loc, fils) would be disregarded
* (undecided regarding distribution - but for consistency with coms, that would change, too)
* summary would continue to indicate the numbers as they are, but with "(? ignored) appended"

One way to tackle this from an implementation point of view could be checking for .git-blame-ignore-revs, which is a pattern / convention which seems to be gaining in popularity, see e.g. https://chromium.googlesource.com/chromium/src.git/+/f0596779e57f46fccb115a0fd65f0305894e3031/.git-blame-ignore-revs

Also, git-blame (https://git-scm.com/docs/git-blame) has a feature that makes it possible to ignore a list of commits quite convenient, either directly on the command-line or by referencing a file (e.g. the .git-blame-ignore-revs from above): `--ignore-revs` and `--ignore-revs-file` as well as the git config option `blame.ignoreRevsFile` (see docs for git blame)

As blame and fame are so closely intertwined, I consider quite appropriate to tack onto (model after) the `blame` configuration options ;)

**Comment by casperdcl** [comment]
> `--ignore-revs` and `--ignore-revs-file`

can you try out #58? (`pip install "git+https://github.com/casperdcl/git-fame@devel#egg=git-fame"`)

> as well as the git config option `blame.ignoreRevsFile`

this is already supported.

**Comment by shoffmeister** [comment]
Wow, thank you very much for this extremely fast and fantastic response!

Let me post some output, then, following that, qualify it:
```
❯ git-fame
Processing: 100%|█████████████████████████████| 9419/9419 [10:33<00:00, 14.87file/s]
Total commits: 29032
Total ctimes: 80802
Total files: 10778
Total loc: 2076437
| Author             |     loc |   coms |   fils |  distribution   |
|:-------------------|--------:|-------:|-------:|:----------------|
| Person 1           | 1313186 |   1446 |   5143 | 63.2/ 5.0/47.7  |
| Person 2           |  251174 |   4103 |   1117 | 12.1/14.1/10.4  |
| Person 3           |  165338 |   5417 |   1209 | 8.0/18.7/11.2   |
| Person 4           |  158857 |   7108 |   1464 | 7.7/24.5/13.6   |
| Person 5           |  130265 |   3973 |   1017 | 6.3/13.7/ 9.4   |
| Person 6           |   52409 |   6380 |    658 | 2.5/22.0/ 6.1   |
| Person 7           |    2874 |    408 |     86 | 0.1/ 1.4/ 0.8   |
| Person 8           |    2334 |    196 |     84 | 0.1/ 0.7/ 0.8   |
| Person 9           |       0 |      1 |      0 | 0.0/ 0.0/ 0.0   |

❯ git-fame --loc=surviving
Processing: 100%|█████████████████████████████| 9419/9419 [10:33<00:00, 14.86file/s]
Total commits: 29032
Total ctimes: 80802
Total files: 10778
Total loc: 2076437
| Author             |     loc |   coms |   fils |  distribution   |
|:-------------------|--------:|-------:|-------:|:----------------|
| Person 1           | 1313186 |   1446 |   5143 | 63.2/ 5.0/47.7  |
| Person 2           |  251174 |   4103 |   1117 | 12.1/14.1/10.4  |
| Person 3           |  165338 |   5417 |   1209 | 8.0/18.7/11.2   |
| Person 4           |  158857 |   7108 |   1464 | 7.7/24.5/13.6   |
| Person 5           |  130265 |   3973 |   1017 | 6.3/13.7/ 9.4   |
| Person 6           |   52409 |   6380 |    658 | 2.5/22.0/ 6.1   |
| Person 7           |    2874 |    408 |     86 | 0.1/ 1.4/ 0.8   |
| Person 8           |    2334 |    196 |     84 | 0.1/ 0.7/ 0.8   |
| Person 9           |       0 |      1 |      0 | 0.0/ 0.0/ 0.0   |

❯ git-fame --loc=surviving --ignore-revs-file ./.git-blame-ignore-revs 
Processing: 100%|█████████████████████████████| 9419/9419 [34:42<00:00,  4.52file/s]
Total commits: 29032
Total ctimes: 268471
Total files: 15014
Total loc: 1638744
| Author             |    loc |   coms |   fils |  distribution   |
|:-------------------|-------:|-------:|-------:|:----------------|
| Person 3           | 417978 |   5417 |   2639 | 25.5/18.7/17.6  |
| Person 4           | 414242 |   7108 |   2933 | 25.3/24.5/19.5  |
| Person 2           | 355242 |   4103 |   1837 | 21.7/14.1/12.2  |
| Person 5           | 187445 |   3973 |   1590 | 11.4/13.7/10.6  |
| Person 1           | 133304 |   1446 |   4226 | 8.1/ 5.0/28.1   |
| Person 6           | 124978 |   6380 |   1604 | 7.6/22.0/10.7   |
| Person 7           |   2875 |    408 |     87 | 0.2/ 1.4/ 0.6   |
| Person 8           |   2680 |    196 |     98 | 0.2/ 0.7/ 0.7   |
| Person 9           |      0 |      1 |      0 | 0.0/ 0.0/ 0.0   |
```

Qualification / comments:
* this is a reasonably old repository, converted about 18 months ago from Subversion to git (relatively cleanly, I think, with reasonably proper author attribution - and there is a mailmap, too)
* I didn't expect any differences between `git-fame` and `git-fame --loc=surviving` - and there are none
* For `git-fame --loc=surviving --ignore-revs-file ./.git-blame-ignore-revs` I used an existing `.git-blame-ignore-revs` ; the effect of applying the option becomes immediately apparent!
  *  "Person 1" sinks in the in the ordered list. This is fully expected, as "Person 1" did a repository-wide line-ending repair, which affected the large majority of files in the repository
  * the changing of positions of Person 3, Person 2 I cannot fully explain; the ignore revs file lists only three commits, all under a heading comment "The great CRLF fixing"... ho-humm?
* the runtime performance numbers for `--ignore-revs-file` are misleading / wrong because during execution the command `git -C ./ blame --line-porcelain --ignore-revs-file ./.git-blame-ignore-revs` evidently hung on, in total, six files. I noticed "too late" that no progress was made on the first stuck file, then waited, waited some more, and eventually sent SIGTERM to the git process. The other "stuck files" I killed faster. Symptoms of the hang were, literally: Processing the affected file (small in size, few commits, I guess) took too long, single core at 100%. This is a `git blame` problem; it reproduces by simply running `git blame` on that file, with ignore revs turned on.

I need to decide what to do about the `git blame` problem - perhaps report that and try to figure out a means to debug that? My git client is
```
git --version 
git version 2.31.1
```

**Comment by shoffmeister** [comment]
Addendum: After thinking about it, excluding CRLF fixing will have the effect that contributions of other authors will grow (significantly). The specific way positions change in the table depends on how many changes these authors made _after_ the CRLF fix was applied.

This is most visible for Person 6, who now gets a much larger number of lines attributed than before - but hasn't committed since the CRLF fix was applied.

Being able to ignore some commits (provided those are "clean"!) is quite enlightening - in that repo, I have just realized the presence of a couple of more commits which would be candidates worthy of un-faming - flipping the logging subsystem, for instance, a relatively mechanistic, yet broad modification.

**Comment by casperdcl** [comment]
FYI `-w`, `-M` and `-C` may be useful flags for you...

**Comment by shoffmeister** [comment]
Many thanks for mentioning the option! I have now traced this down to performance of git blame degenerating under some circumstances.

An extract from my email to the main git mailing list (https://public-inbox.org/git/CALhB_QNf98O=kOnZ=rmUt90SmqZzxRF2CfyYOKiiJv+Qa2abqg@mail.gmail.com/T/#u)
```
* git blame --ignore-rev degenerate performance on large(r) line counts
@ 2021-08-01 12:58 Stefan Hoffmeister
  0 siblings, 0 replies; only message in thread
From: Stefan Hoffmeister @ 2021-08-01 12:58 UTC (permalink / raw)
  To: git

git blame has a very useful option --ignore-rev (or --ignore-rev-file)
which allows ignoring of commits for the purpose of attributing blame.

One use case for this option is a scenario where a repository was
"cleaned" up for line breaks, e.g. via "git add --renormalize ."

Alas, git blame with --ignore-rev will fall apart at runtime whenever
the number of lines of code affected is high; it will show exponential
increases in execution duration on linearly increasing line counts.

The Python script below demonstrates ...
```
