### ISSUE TITLE
Excluding a folder

### ISSUE THREAD

**Issue by RamuRChenchaiah** [casperdcl/git-fame#66]
Hi There,

Would you please advice on how to exclude a folder (for example .git folder)?

Thanks

**Comment by casperdcl** [comment]
`--excl` uses regex (e.g. `--excl=".*[\\/]some_folder[\\/].*")

**Comment by casperdcl** [comment]
Closing for now; happy to reopen if further clarification is needed.

**Comment by RagnarDa** [comment]
Seems to not work for me either. I tried using the suggested --excl and several versions of it and it always returned the same loc. Using homebrew version.
