### ISSUE TITLE
What is `--loc=surv`?

### ISSUE THREAD

**Issue by movahhedi** [casperdcl/git-fame#75]
Hello
What is `--loc=surv`? I can't find any definition for it anywhere, neither in the repo, nor anywhere on the net. When to use it?

**Comment by casperdcl** [comment]
Surviving lines of code (i.e. only currently existing lines, not deleted ones)

**Comment by casperdcl** [comment]
do let me know if it's not clear enough :)

**Comment by movahhedi** [comment]
Thanks for answering.
If it counts lines (files?) which exist now, how is the contribution on one specific line counted? Does it just count the last rivision on that line?

Look, I'm looking for the best way to measure how much I have to pay my devs. What is your  suggestion for it? Is it `git fame --loc=surv -w -C`? Is it even using git statics at all?

**Comment by casperdcl** [comment]
> Does it just count the last r[e]vision on that line?

`--loc=surv` indeed counts "just the last revision on that line." It may be useful to also include `-M` and `-C` options.

> looking for the best way to measure how much I have to pay my devs.

Here be dragons :dragon: ... the `--cost` options can guesstimate hours & months using different models as per https://github.com/casperdcl/git-fame#faqs - but note:

- there's no way to distinguish between refactoring (presumably high value) & reformatting (presumably lower value)
- one line of code may be more valuable than 100. Quality can only be measured by a human
- reviewing other people's code may be valuable but doesn't show up in Git history
- ... the list of caveats goes on.

I would at best use `git fame` as one of many many ways to help gauge the true value of contributions. I would *not* suggest paying people solely based on number/rate of commits/lines.

**Comment by movahhedi** [comment]
I truly value your answer, It is indeed very helpful. Thanks 😊
