### ISSUE TITLE
Double -C option

### ISSUE THREAD

**Issue by zapadinsky** [casperdcl/git-fame#9]
Git blame command has a weird -C option:
`When this option is given twice, the command additionally looks for copies from other files in the commit that creates the file`

I don't think that this syntax should be copied here probably just change `git_blame_cmd.append("-C")` to `git_blame_cmd.append("-C -C")`. Otherwise it attributes all the lines in a newly created file to its committer even if it is a complete copy of an already existed file.

**Comment by casperdcl** [comment]
thanks @zapadinsky
